name: Build and Test Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install

      - name: Build Android
        run: |
          npx react-native run-android --variant=release

      - name: Run tests
        run: |
          # Add your test command here

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/
