name: Build and Test Android

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Android
        run: |
          npx react-native run-android --variant=release

      - name: Run tests
        run: |
          # Ajouter la commande de test ici

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/
